---
- name: Install MadiaDB
  yum:
    name: mariadb-server
    state: present
- name: Install the Python MySQL Support Libraries
  yum: 
    pkg: MySQL-python 
    state: latest
- name: start mysql server and enable it on reboot
  service: 
    name: mariadb 
    state: started 
    enabled: true
- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_password }}"
    login_user: root
    login_password: "{{ mysql_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
- name: Copy the root credentials as .my.cnf file
  template: 
    src: my.cnf.j2 
    dest: ~/.my.cnf
    mode: '0600'
- name: Copy schema
  copy:
    src: "{{ item }}"
    dest: /tmp/ 
  with_items:
    - 001-create-schema.sql
    - 002-create-admin-user.sql
    - guacamole-auth-jdbc-mysql-1.0.0.jar
- name: Create a New Test DB called guac_db and import schema
  mysql_db: 
    name: guac_db
    state: present 
    login_user: root 
    login_password: "{{ mysql_password }}"
  ignore_errors: yes
- mysql_db:
    login_user: root
    login_password: "{{ mysql_password }}"
    state: import
    name: guac_db
    target: "/tmp/{{ item }}"
  with_items:
    - 001-create-schema.sql
    - 002-create-admin-user.sql
  ignore_errors: yes
- name: Copy tomcat files
  file:
    path: /usr/share/tomcat/.guacamole/
    state: directory
    owner: root
    group: tomcat
    recurse: yes
- file:
    path: /usr/share/tomcat/.guacamole/extensions/
    state: directory
    owner: root
    group: tomcat
    recurse: yes
- copy:
    src: /usr/share/java/mysql-connector-java.jar
    remote_src: yes
    dest: /usr/share/tomcat/lib/
- copy:
    src: /tmp/guacamole-auth-jdbc-mysql-1.0.0.jar
    remote_src: yes
    dest: /usr/share/tomcat/.guacamole/extensions/
- name: Config MariaDB
  template:
    src: guacamole.properties.j2
    dest: /usr/share/tomcat/.guacamole/guacamole.properties
    owner: root
    group: tomcat
- name: Restart tomcat
  service:
    name: tomcat
    state: restarted

